### ISSUE TITLE
Download AWS files using formula field and MW API call

### ISSUE THREAD

**Issue by gvpatel** [pozil/sf-docs-from-s3#2]
Hi @pozil,

We've following requirement regarding getting file from AWS.

1. External System loads aws file medata in Salesforce custom object using dataloader.
2. Salesforce object is using formula field with hyperlink using aws file attributes
3. User clicks formula field and call Middleware API (with hyperlink - using step2)  where  the click should authenticate MW using oauth2 with MW being auth. provider ( here is sample url - https://dev1-mw-api.business.aws.lexis.com/v1/getpresignedurl?objectKey=statements/description.pdf)
4. MW sends aws presigned url  which will be valid for 30 min and Salesforce will have to open in new browser window to download the file

Is it possible using Salesforce formula field? what options do we've to implement this requirment?

Appreciate any input.

Thanks,

**Comment by pozil** [comment]
Not sure to understand why you'd need a formula field. Can't you could directly prepare and upload the right URLs in step 1?

Anyways, I think that this is mostly feasible (not sure about the time constraint in step 4) but this is unrelated to this repository.

**Comment by gvpatel** [comment]
Thanks @pozil,

We're using formula field with the hyperlink which calls MW api and we pass aws file name as parameter so MW team is asking SF team to authorize MW Api using oauth. MW is auth provider so is it possible to do that using hyperlink click?

I get following error so we need to authorize MW before AWS file retrieval call is made

so how can we do that?

<img width="928" alt="image" src="https://user-images.githubusercontent.com/18720022/189429696-88804042-58fa-4080-9dac-f58b3f899912.png">

**Comment by pozil** [comment]
Hi @gvpatel, again your project is very different from what I'm doing in this repository so I'm not going to be able to help.
In this repo, the Heroku app takes care of both the Salesforce and AWS authentication. I can only comment on this.
